### ISSUE TITLE
Trails gis query throwing an error

### ISSUE THREAD

**Issue by smcalilly** [fpdcc/ccfp-asset-dashboard#241]
From an email:

> One issue I already encountered was I couldn’t select trail data when I was creating new projects. I was able to see the selected segments in existing projects though. So please take a look at that.

I was able to recreate this on production.

**Comment by smcalilly** [comment]
2023-06-20T17:01:30.462258+00:00 heroku[router]: at=info method=GET path="/assets/?q=busse&asset_type=trails" host=ccfp-asset-dashboard-staging.herokuapp.com request_id=ed26142c-f35a-406f-b3fe-9a08f367994a fwd="108.248.50.187" dyno=web.1 connect=0ms service=120ms status=500 bytes=3784 protocol=https
2023-06-20T17:01:49.227051+00:00 app[web.1]: [2023-06-20 17:01:49 +0000] [16] [DEBUG] GET /assets/
2023-06-20T17:01:53.175383+00:00 app[web.1]: Internal Server Error: /assets/
2023-06-20T17:01:53.175411+00:00 app[web.1]: Traceback (most recent call last):
2023-06-20T17:01:53.175412+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
2023-06-20T17:01:53.175412+00:00 app[web.1]: return self.cursor.execute(sql, params)
2023-06-20T17:01:53.175413+00:00 app[web.1]: psycopg2.errors.UndefinedColumn: column trails_info.trails_id does not exist
2023-06-20T17:01:53.175413+00:00 app[web.1]: LINE 1: SELECT "quercus"."trails_info"."trail_info_id", "quercus"."t...
2023-06-20T17:01:53.175414+00:00 app[web.1]: ^
2023-06-20T17:01:53.175414+00:00 app[web.1]:
2023-06-20T17:01:53.175414+00:00 app[web.1]:
2023-06-20T17:01:53.175415+00:00 app[web.1]: The above exception was the direct cause of the following exception:
2023-06-20T17:01:53.175415+00:00 app[web.1]:
2023-06-20T17:01:53.175415+00:00 app[web.1]: Traceback (most recent call last):
2023-06-20T17:01:53.175415+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
2023-06-20T17:01:53.175416+00:00 app[web.1]: response = get_response(request)
2023-06-20T17:01:53.175487+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
2023-06-20T17:01:53.175617+00:00 app[web.1]: response = wrapped_callback(request, *callback_args, **callback_kwargs)
2023-06-20T17:01:53.175618+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
2023-06-20T17:01:53.175618+00:00 app[web.1]: return view_func(*args, **kwargs)
2023-06-20T17:01:53.175619+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
2023-06-20T17:01:53.175619+00:00 app[web.1]: return self.dispatch(request, *args, **kwargs)
2023-06-20T17:01:53.175619+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
2023-06-20T17:01:53.175620+00:00 app[web.1]: response = self.handle_exception(exc)
2023-06-20T17:01:53.175620+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
2023-06-20T17:01:53.175620+00:00 app[web.1]: self.raise_uncaught_exception(exc)
2023-06-20T17:01:53.175621+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
2023-06-20T17:01:53.175621+00:00 app[web.1]: raise exc
2023-06-20T17:01:53.175621+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
2023-06-20T17:01:53.175621+00:00 app[web.1]: response = handler(request, *args, **kwargs)
2023-06-20T17:01:53.175622+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/rest_framework/mixins.py", line 46, in list
2023-06-20T17:01:53.175622+00:00 app[web.1]: return Response(serializer.data)
2023-06-20T17:01:53.175622+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/rest_framework_gis/serializers.py", line 23, in data
2023-06-20T17:01:53.175622+00:00 app[web.1]: return super(ListSerializer, self).data
2023-06-20T17:01:53.175623+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 253, in data
2023-06-20T17:01:53.175623+00:00 app[web.1]: self._data = self.to_representation(self.instance)
2023-06-20T17:01:53.175623+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/rest_framework_gis/serializers.py", line 32, in to_representation
2023-06-20T17:01:53.175624+00:00 app[web.1]: ("features", super().to_representation(data)),
2023-06-20T17:01:53.175624+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 686, in to_representation
2023-06-20T17:01:53.175624+00:00 app[web.1]: return [
2023-06-20T17:01:53.175624+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 287, in __iter__
2023-06-20T17:01:53.175625+00:00 app[web.1]: self._fetch_all()
2023-06-20T17:01:53.175625+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1308, in _fetch_all
2023-06-20T17:01:53.175625+00:00 app[web.1]: self._result_cache = list(self._iterable_class(self))
2023-06-20T17:01:53.175626+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 53, in __iter__
2023-06-20T17:01:53.175626+00:00 app[web.1]: results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
2023-06-20T17:01:53.175626+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
2023-06-20T17:01:53.175626+00:00 app[web.1]: cursor.execute(sql, params)
2023-06-20T17:01:53.175627+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
2023-06-20T17:01:53.175627+00:00 app[web.1]: return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
2023-06-20T17:01:53.175627+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
2023-06-20T17:01:53.175627+00:00 app[web.1]: return executor(sql, params, many, context)
2023-06-20T17:01:53.175628+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
2023-06-20T17:01:53.175628+00:00 app[web.1]: return self.cursor.execute(sql, params)
2023-06-20T17:01:53.175628+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
2023-06-20T17:01:53.175628+00:00 app[web.1]: raise dj_exc_value.with_traceback(traceback) from exc_value
2023-06-20T17:01:53.175629+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
2023-06-20T17:01:53.175629+00:00 app[web.1]: return self.cursor.execute(sql, params)
2023-06-20T17:01:53.175629+00:00 app[web.1]: django.db.utils.ProgrammingError: column trails_info.trails_id does not exist
2023-06-20T17:01:53.175630+00:00 app[web.1]: LINE 1: SELECT "quercus"."trails_info"."trail_info_id", "quercus"."t...
