### ISSUE TITLE
Users unable to delete assets

### ISSUE THREAD

**Issue by hallj89** [fpdcc/ccfp-asset-dashboard#252]
https://ccfp-asset-dashboard-prod.herokuapp.com/projects/76/

Duplicate assets added accidentally and can't be removed. Delete button doesn't respond, or after refresh gives internal server error then successful delete message while not actually removing anything.

**Comment by smcalilly** [comment]
from the logs:

```
2023-08-02T15:59:26.537819+00:00 app[web.1]: self.project.update_project_districts(self.phase_geometries)
2023-08-02T15:59:26.537819+00:00 app[web.1]: File "/app/asset_dashboard/models.py", line 156, in update_project_districts
2023-08-02T15:59:26.537819+00:00 app[web.1]: for district in districts:
2023-08-02T15:59:26.537820+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 280, in __iter__
2023-08-02T15:59:26.537820+00:00 app[web.1]: self._fetch_all()
2023-08-02T15:59:26.537820+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
2023-08-02T15:59:26.537820+00:00 app[web.1]: self._result_cache = list(self._iterable_class(self))
2023-08-02T15:59:26.537821+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
2023-08-02T15:59:26.537821+00:00 app[web.1]: results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
2023-08-02T15:59:26.537821+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
2023-08-02T15:59:26.537821+00:00 app[web.1]: cursor.execute(sql, params)
2023-08-02T15:59:26.537823+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/django/__init__.py", line 499, in execute
2023-08-02T15:59:26.537823+00:00 app[web.1]: return real_execute(self, sql, params)
2023-08-02T15:59:26.537823+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
2023-08-02T15:59:26.537823+00:00 app[web.1]: return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
2023-08-02T15:59:26.537824+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
2023-08-02T15:59:26.537824+00:00 app[web.1]: return executor(sql, params, many, context)
2023-08-02T15:59:26.537824+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
2023-08-02T15:59:26.537824+00:00 app[web.1]: return self.cursor.execute(sql, params)
2023-08-02T15:59:26.537824+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
2023-08-02T15:59:26.537825+00:00 app[web.1]: raise dj_exc_value.with_traceback(traceback) from exc_value
2023-08-02T15:59:26.537825+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
2023-08-02T15:59:26.537825+00:00 app[web.1]: return self.cursor.execute(sql, params)
2023-08-02T15:59:26.537825+00:00 app[web.1]: django.db.utils.OperationalError: SSL SYSCALL error: EOF detected
2023-08-02T15:59:26.537825+00:00 app[web.1]:
2023-08-02T15:59:26.537825+00:00 app[web.1]:
2023-08-02T15:59:26.537826+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2023-08-02T15:59:26.537826+00:00 app[web.1]:
2023-08-02T15:59:26.537826+00:00 app[web.1]: Traceback (most recent call last):
2023-08-02T15:59:26.537826+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
2023-08-02T15:59:26.537826+00:00 app[web.1]: self.connect()
2023-08-02T15:59:26.537826+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
2023-08-02T15:59:26.537827+00:00 app[web.1]: return func(*args, **kwargs)
2023-08-02T15:59:26.537827+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
2023-08-02T15:59:26.537827+00:00 app[web.1]: self.connection = self.get_new_connection(conn_params)
2023-08-02T15:59:26.537827+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
2023-08-02T15:59:26.537827+00:00 app[web.1]: return func(*args, **kwargs)
2023-08-02T15:59:26.537827+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
2023-08-02T15:59:26.537827+00:00 app[web.1]: connection = Database.connect(**conn_params)
2023-08-02T15:59:26.537828+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
2023-08-02T15:59:26.537828+00:00 app[web.1]: conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
2023-08-02T15:59:26.537828+00:00 app[web.1]: psycopg2.OperationalError: FATAL:  the database system is in recovery mode
2023-08-02T15:59:26.537828+00:00 app[web.1]: FATAL:  the database system is in recovery mode
2023-08-02T15:59:26.537828+00:00 app[web.1]:
2023-08-02T15:59:26.537828+00:00 app[web.1]:
2023-08-02T15:59:26.537829+00:00 app[web.1]: The above exception was the direct cause of the following exception:
2023-08-02T15:59:26.537829+00:00 app[web.1]:
2023-08-02T15:59:26.537829+00:00 app[web.1]: Traceback (most recent call last):
2023-08-02T15:59:26.537829+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
2023-08-02T15:59:26.537832+00:00 app[web.1]: response = get_response(request)
2023-08-02T15:59:26.537832+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
2023-08-02T15:59:26.537833+00:00 app[web.1]: response = wrapped_callback(request, *callback_args, **callback_kwargs)
2023-08-02T15:59:26.537833+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
2023-08-02T15:59:26.537833+00:00 app[web.1]: return callback(request, *args, **kwargs)
2023-08-02T15:59:26.537833+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
2023-08-02T15:59:26.537833+00:00 app[web.1]: return view_func(*args, **kwargs)
2023-08-02T15:59:26.537834+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
2023-08-02T15:59:26.537834+00:00 app[web.1]: return self.dispatch(request, *args, **kwargs)
2023-08-02T15:59:26.537834+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
2023-08-02T15:59:26.537834+00:00 app[web.1]: response = self.handle_exception(exc)
2023-08-02T15:59:26.537834+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
2023-08-02T15:59:26.537834+00:00 app[web.1]: self.raise_uncaught_exception(exc)
2023-08-02T15:59:26.537834+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
2023-08-02T15:59:26.537835+00:00 app[web.1]: raise exc
2023-08-02T15:59:26.537835+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
2023-08-02T15:59:26.537835+00:00 app[web.1]: response = handler(request, *args, **kwargs)
2023-08-02T15:59:26.537837+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/rest_framework/mixins.py", line 91, in destroy
2023-08-02T15:59:26.537837+00:00 app[web.1]: self.perform_destroy(instance)
2023-08-02T15:59:26.537837+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/rest_framework/mixins.py", line 95, in perform_destroy
2023-08-02T15:59:26.537837+00:00 app[web.1]: instance.delete()
2023-08-02T15:59:26.537838+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 967, in delete
2023-08-02T15:59:26.537838+00:00 app[web.1]: return collector.delete()
2023-08-02T15:59:26.537838+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/db/models/deletion.py", line 435, in delete
2023-08-02T15:59:26.537838+00:00 app[web.1]: signals.post_delete.send(
2023-08-02T15:59:26.537838+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/db/transaction.py", line 290, in __exit__
2023-08-02T15:59:26.537839+00:00 app[web.1]: connection.set_autocommit(True)
2023-08-02T15:59:26.537839+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 405, in set_autocommit
2023-08-02T15:59:26.537839+00:00 app[web.1]: self.ensure_connection()
2023-08-02T15:59:26.537839+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
2023-08-02T15:59:26.537839+00:00 app[web.1]: return func(*args, **kwargs)
2023-08-02T15:59:26.537839+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
2023-08-02T15:59:26.537840+00:00 app[web.1]: self.connect()
2023-08-02T15:59:26.537840+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
2023-08-02T15:59:26.537840+00:00 app[web.1]: raise dj_exc_value.with_traceback(traceback) from exc_value
2023-08-02T15:59:26.537840+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
2023-08-02T15:59:26.537840+00:00 app[web.1]: self.connect()
2023-08-02T15:59:26.537840+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
2023-08-02T15:59:26.537840+00:00 app[web.1]: return func(*args, **kwargs)
2023-08-02T15:59:26.537841+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
2023-08-02T15:59:26.537841+00:00 app[web.1]: self.connection = self.get_new_connection(conn_params)
2023-08-02T15:59:26.537841+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
2023-08-02T15:59:26.537841+00:00 app[web.1]: return func(*args, **kwargs)
2023-08-02T15:59:26.537841+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
2023-08-02T15:59:26.537841+00:00 app[web.1]: connection = Database.connect(**conn_params)
2023-08-02T15:59:26.537842+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
2023-08-02T15:59:26.537842+00:00 app[web.1]: conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
2023-08-02T15:59:26.537842+00:00 app[web.1]: django.db.utils.OperationalError: FATAL:  the database system is in recovery mode
2023-08-02T15:59:26.537842+00:00 app[web.1]: FATAL:  the database system is in recovery mode
2023-08-02T15:59:26.537842+00:00 app[web.1]:
2023-08-02T15:59:26.539388+00:00 heroku[router]: at=info method=DELETE path="/local-assets/402/" host=ccfp-asset-dashboard-prod.herokuapp.com request_id=e8c6925e-352f-4799-ad35-7bd84246411a fwd="158.120.137.32" dyno=web.1 connect=0ms service=439ms status=500 bytes=3784 protocol=https
```

**Comment by smcalilly** [comment]
this might be the fix: https://devcenter.heroku.com/articles/postgres-connection-pooling

**Comment by smcalilly** [comment]
This is the same problem we had in #224 

The GEOS version in Heroku's postgres version creates the segmentation fault (at least this is the working theory, see https://trac.osgeo.org/postgis/ticket/4894).

@fgregg you mentioned this https://github.com/heroku/heroku-geo-buildpack as a potential fix ([re this comment](https://github.com/fpdcc/ccfp-asset-dashboard/issues/224#issuecomment-1549760257)). We set it aside because we're going to move to CCFP's servers, but I'm not sure where that's at with their staff changes. Should we go ahead and try that buildpack?

**Comment by fgregg** [comment]
yes, i think the webpack makes sense.

**Comment by smcalilly** [comment]
I'm going to setup a very cheap Postgres instance on AWS RDS to see if this will work as the primary database for the app. It must have postgis with a GEOS > 3`.8.0-CAPI-1.13.1`.

- [] setup RDS instance
- [] install postgis extension
- [] dump production data into db
- [] connect with staging app
- [] test gis bug
- [] if it works, setup the db to be used in production (including backups, etc, what all do we need for that?)
